### ISSUE TITLE
[Feature][前台] 文章功能加上 Page Builder

### ISSUE THREAD

**Issue by AngelaLiu-24** [lyrasoft/eva#36]
文章功能加上 Page Builder --> 參考台北政經學院（清大）

<img width="1429" alt="175896230-b453310b-58dd-4e50-8c86-b6be3824cfdc" src="https://user-images.githubusercontent.com/72063525/177466758-fab96e4c-09a2-42a8-8e94-ff0050517025.png">

相關聯的 issue：https://github.com/lyrasoft/nthu-ctm/issues/9

**Comment by asika32764** [comment]
已經有了，可以先用 eva 測試，再請工程師更新套件

http://demo.lyrasoft.net/eva/www/article/98-consequatur-modi-voluptatibus-non

**Comment by AngelaLiu-24** [comment]
測試 OK
