### ISSUE TITLE
[Update]頁面編輯後，前台無法顯示出調整

### ISSUE THREAD

**Issue by chungkai0911** [lyrasoft/eva#46]
[後台頁面](https://demo.lyrasoft.net/eva/www/admin/page/edit/50)
[前台頁面](https://demo.lyrasoft.net/eva/www/dev.php/page/leihuo-fong-lyu-shuang-jianbing-syun-jhih-chi-dao?preview=ZBgW.35N9O5V)

- [ ] 已將編輯後的文字復原。
![screenshot 2023-09-07 12 31 18](https://github.com/lyrasoft/eva/assets/113872214/659c0f3a-e053-46a3-a3a9-3d8afc1ec768)

- [ ] 前台還是顯示編輯前的樣貌。先前可以調整是有先請Yinmin更新過，需要確認是不是快取的問題。
![screenshot 2023-09-07 12 31 13](https://github.com/lyrasoft/eva/assets/113872214/2c4100ee-ddee-4bdf-a2e6-1a3a96dca22d)

**Comment by chokeslam** [comment]
windwalker 4.0 已修在 [#474](https://github.com/lyrasoft/luna/pull/474)

**Comment by chungkai0911** [comment]
待套件更新後測試。

**Comment by chungkai0911** [comment]
測試確認，關閉issue：
![screenshot 2024-01-10 09 50 21](https://github.com/lyrasoft/eva/assets/113872214/80fa77fe-cd67-41cf-8bb8-4284cd68e230)
![screenshot 2024-01-10 09 50 02](https://github.com/lyrasoft/eva/assets/113872214/9b7026d1-0541-44cc-832c-9822aed59e81)
