### ISSUE TITLE
[Update] 後台 / 用戶 使用者管理- 重寄驗證信要裝symfony/mailer

### ISSUE THREAD

**Issue by ginnyhuang1** [lyrasoft/eva#8]
![image](https://user-images.githubusercontent.com/94339519/143532695-ed78e9b0-0bc5-4e10-afd6-ba61a144c07c.png)

**Comment by bebe0923** [comment]
中文翻譯另外開，這邊先關閉https://github.com/lyrasoft/eva/issues/39
